[package]
name = "xxnetwork-cli"
version = "0.2.3"
authors = ["xxlabs <admin@xx.network>"]
description = "Substrate based, xxnetwork blockchain node implementation in Rust."
build = "build.rs"
edition = "2021"
default-run = "xxnetwork-chain"
homepage = "https://xx.network"
repository = "https://github.com/xx-labs/xxchain/"

[package.metadata.wasm-pack.profile.release]
# `wasm-opt` has some problems on linux, see
# https://github.com/rustwasm/wasm-pack/issues/781 etc.
wasm-opt = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
name = "xxnetwork-chain"
path = "bin/main.rs"
required-features = ["cli"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# third-party dependencies
codec = { package = "parity-scale-codec", version = "2.0.0" }
serde = { version = "1.0.126", features = ["derive"] }
futures = "0.3.16"
hex-literal = "0.3.3"
log = "0.4.8"
rand = "0.7.2"
structopt = { version = "0.3.8", optional = true }

# primitives
sp-authority-discovery = { git = "https://github.com/xx-labs/substrate", branch = "xx-network" }
sp-consensus-babe = { git = "https://github.com/xx-labs/substrate", branch = "xx-network" }
grandpa-primitives = { git = "https://github.com/xx-labs/substrate", branch = "xx-network", package = "sp-finality-grandpa" }
sp-api = { git = "https://github.com/xx-labs/substrate", branch = "xx-network" }
sp-core = { git = "https://github.com/xx-labs/substrate", branch = "xx-network" }
sp-runtime = { git = "https://github.com/xx-labs/substrate", branch = "xx-network" }
sp-timestamp = { git = "https://github.com/xx-labs/substrate", branch = "xx-network" }
sp-authorship = { git = "https://github.com/xx-labs/substrate", branch = "xx-network" }
sp-inherents = { git = "https://github.com/xx-labs/substrate", branch = "xx-network" }
sp-keyring = { git = "https://github.com/xx-labs/substrate", branch = "xx-network" }
sp-keystore = { git = "https://github.com/xx-labs/substrate", branch = "xx-network" }
sp-consensus = { git = "https://github.com/xx-labs/substrate", branch = "xx-network" }
sp-transaction-pool = { git = "https://github.com/xx-labs/substrate", branch = "xx-network" }
sp-transaction-storage-proof = { git = "https://github.com/xx-labs/substrate", branch = "xx-network" }
sp-block-builder = { git = "https://github.com/xx-labs/substrate", branch = "xx-network" }
sp-offchain = { git = "https://github.com/xx-labs/substrate", branch = "xx-network" }
sp-session = { git = "https://github.com/xx-labs/substrate", branch = "xx-network" }

# client dependencies
sc-client-api = { git = "https://github.com/xx-labs/substrate", branch = "xx-network" }
sc-chain-spec = { git = "https://github.com/xx-labs/substrate", branch = "xx-network" }
sc-consensus = { git = "https://github.com/xx-labs/substrate", branch = "xx-network" }
sc-transaction-pool = { git = "https://github.com/xx-labs/substrate", branch = "xx-network" }
sc-transaction-pool-api = { git = "https://github.com/xx-labs/substrate", branch = "xx-network" }
sc-network = { git = "https://github.com/xx-labs/substrate", branch = "xx-network" }
sc-consensus-slots = { git = "https://github.com/xx-labs/substrate", branch = "xx-network" }
sc-consensus-babe = { git = "https://github.com/xx-labs/substrate", branch = "xx-network" }
sc-consensus-uncles = { git = "https://github.com/xx-labs/substrate", branch = "xx-network" }
grandpa = { git = "https://github.com/xx-labs/substrate", branch = "xx-network", package = "sc-finality-grandpa" }
sc-rpc = { git = "https://github.com/xx-labs/substrate", branch = "xx-network" }
sc-basic-authorship = { git = "https://github.com/xx-labs/substrate", branch = "xx-network" }
sc-service = { git = "https://github.com/xx-labs/substrate", branch = "xx-network", default-features = false }
sc-telemetry = { git = "https://github.com/xx-labs/substrate", branch = "xx-network" }
sc-executor = { git = "https://github.com/xx-labs/substrate", branch = "xx-network" }
sc-authority-discovery = { git = "https://github.com/xx-labs/substrate", branch = "xx-network" }
sc-sync-state-rpc = { git = "https://github.com/xx-labs/substrate", branch = "xx-network" }

# frame dependencies
frame-system = { git = "https://github.com/xx-labs/substrate", branch = "xx-network" }
frame-system-rpc-runtime-api = { git = "https://github.com/xx-labs/substrate", branch = "xx-network" }
pallet-transaction-payment = { git = "https://github.com/xx-labs/substrate", branch = "xx-network" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/xx-labs/substrate", branch = "xx-network" }
pallet-im-online = { git = "https://github.com/xx-labs/substrate", branch = "xx-network", default-features = false }

# node-specific dependencies
xxnetwork-runtime = { version = "0.2.3", path = "../runtime/xxnetwork", optional = true }
protonet-runtime = { version = "0.2.0", path = "../runtime/protonet", optional = true }
phoenixx-runtime = { version = "0.2.0", path = "../runtime/phoenixx", optional = true }
node-rpc = { version = "0.2.0", path = "../rpc" }
node-primitives = { version = "0.2.0", path = "../primitives" }
node-executor = { version = "0.2.0", path = "../executor" }
runtime-common = { version = "0.2.0", path = "../runtime/common" }

# CLI-specific dependencies
sc-cli = { git = "https://github.com/xx-labs/substrate", branch = "xx-network", optional = true }
frame-benchmarking-cli = { git = "https://github.com/xx-labs/substrate", branch = "xx-network", optional = true }
node-inspect = { version = "0.2.0", optional = true, path = "../inspect" }
try-runtime-cli = { git = "https://github.com/xx-labs/substrate", branch = "xx-network", optional = true }

[target.'cfg(target_arch="x86_64")'.dependencies]
node-executor = { version = "0.2.0", path = "../executor", features = [ "wasmtime" ] }
sc-cli = { git = "https://github.com/xx-labs/substrate", branch = "xx-network", optional = true, features = [ "wasmtime" ] }
sc-service = { git = "https://github.com/xx-labs/substrate", branch = "xx-network", default-features = false, features = [ "wasmtime" ] }
sp-trie = { git = "https://github.com/xx-labs/substrate", branch = "xx-network", default-features = false, features = ["memory-tracker"] }

[dev-dependencies]
sc-keystore = { git = "https://github.com/xx-labs/substrate", branch = "xx-network" }
sc-client-db = { git = "https://github.com/xx-labs/substrate", branch = "xx-network" }
sc-consensus = { git = "https://github.com/xx-labs/substrate", branch = "xx-network" }
sc-consensus-babe = { git = "https://github.com/xx-labs/substrate", branch = "xx-network" }
sc-consensus-epochs = { git = "https://github.com/xx-labs/substrate", branch = "xx-network" }
sc-service-test = { git = "https://github.com/xx-labs/substrate", branch = "xx-network" }
sp-tracing = { git = "https://github.com/xx-labs/substrate", branch = "xx-network" }
futures = "0.3.16"
tempfile = "3.1.0"
assert_cmd = "2.0.2"
nix = "0.23"
serde_json = "1.0"
regex = "1"
platforms = "1.1"
async-std = { version = "1.10.0", features = ["attributes"] }
soketto = "0.4.2"
criterion = { version = "0.3.5", features = [ "async_tokio" ] }
tokio = { version = "1.10", features = ["macros", "time"] }
jsonrpsee-ws-client = { version = "0.3.1", default-features = false, features = ["tokio1"] }
wait-timeout = "0.2"
remote-externalities = { git = "https://github.com/xx-labs/substrate", branch = "xx-network" }

[build-dependencies]
structopt = { version = "0.3.8", optional = true }
node-inspect = { version = "0.2.0", optional = true, path = "../inspect" }
frame-benchmarking-cli = { git = "https://github.com/xx-labs/substrate", branch = "xx-network", optional = true }
substrate-build-script-utils = { git = "https://github.com/xx-labs/substrate", branch = "xx-network", optional = true }
substrate-frame-cli = { git = "https://github.com/xx-labs/substrate", branch = "xx-network", optional = true }
try-runtime-cli = { git = "https://github.com/xx-labs/substrate", branch = "xx-network", optional = true }
sc-cli = { git = "https://github.com/xx-labs/substrate", branch = "xx-network", optional = true }
pallet-balances = { git = "https://github.com/xx-labs/substrate", branch = "xx-network" }

[features]
default = ["cli", "xxnetwork"]
cli = [
	"node-executor/wasmi-errno",
	"node-inspect",
	"sc-cli",
	"frame-benchmarking-cli",
	"substrate-frame-cli",
	"sc-service/db",
	"structopt",
	"substrate-build-script-utils",
	"try-runtime-cli",
]
runtime-benchmarks = [
	"xxnetwork-runtime/runtime-benchmarks",
	# "protonet-runtime/runtime-benchmarks",
	# "phoenixx-runtime/runtime-benchmarks",
	"frame-benchmarking-cli",
]
# Enable features that allow the runtime to be tried and debugged. Name might be subject to change
# in the near future.
try-runtime = [
	"xxnetwork-runtime/try-runtime",
	"protonet-runtime/try-runtime",
	"phoenixx-runtime/try-runtime",
	"try-runtime-cli",
]

xxnetwork = ["xxnetwork-runtime", "node-executor/xxnetwork"]
protonet = ["protonet-runtime", "node-executor/protonet"]
phoenixx = ["phoenixx-runtime", "node-executor/phoenixx"]

fast-runtime = [
	"xxnetwork-runtime/fast-runtime",
]
